"""Expand the registry matrix into experiment config YAMLs.

For every valid ``(env, actor, modality)`` this emits one prediction config at
``<catalog>/configs/prediction/<env>/<points>pt_<dataset_id>_<actor>_<modality>.yaml``
and for every ``(env, gt_actor)`` one ground-truth config
``…/<gt_points>pt_<dataset_id>_<gt_actor>_gt.yaml``. Paths are catalog-relative
(written under the catalog root); every ``predictions_dir`` is derived from
:mod:`qval.registry.naming`, so ``predict.py`` writes its output (eval/gt
artifacts, rollouts, logs) into the canonical location with no hand-typed path.
Generated files carry a ``DO NOT EDIT`` header — the catalog is the thing you edit.

The generator only ever *references* shared backends
(``shared/configs/backends.yaml``) and contexts (``shared/configs/environments/``)
by name; it never creates or edits either.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import yaml

from qval.registry import naming
from qval.registry.active import active_registry
from qval.registry.applicability import is_applicable, signals_for
from qval.registry.atoms import (
    EnvironmentSpec,
    MethodSpec,
    Modality,
    ModelSpec,
    Registry,
    Signal,
)

_HEADER = (
    "# GENERATED by scripts/generate_configs.py from the active catalog.\n"
    "# DO NOT EDIT — change the catalog and regenerate.\n"
)
_BACKENDS_CONFIG = "shared/configs/backends.yaml"


@dataclass(frozen=True)
class GeneratedConfig:
    """One config file the generator owns: ``path`` is catalog-relative."""

    path: str
    text: str
    kind: str  # "eval" | "gt"
    env: str


# --- backend resolution ----------------------------------------------------
def resolve_backend(
    method: MethodSpec, model: ModelSpec, modality: Modality
) -> str | None:
    """The backend name to reference for ``method`` run by ``model``.

    Pinned pre-trained methods (vip / liv) supply their own backbone; embedding
    methods (vle) use the clip/siglip actor's backbone; plain-LLM methods use
    the actor's backend (codegen variant for the Code family, vision variant
    under vision when one is set, else the base).
    """
    if method.backend_override is not None:
        return method.backend_override
    if method.requires_embedding_backbone:
        return model.backend_base
    return model.backend_for(
        codegen=method.family == "Code",
        vision=modality is Modality.VISION,
    )


# --- rendering -------------------------------------------------------------
def _render(body: dict) -> str:
    return _HEADER + yaml.safe_dump(
        body, sort_keys=False, default_flow_style=False, allow_unicode=True
    )


def _yamlable(value: object) -> object:
    """Coerce hashable registry values into YAML-native ones (tuple -> list)."""
    if isinstance(value, tuple):
        return [_yamlable(v) for v in value]
    return value


def _method_entry(
    method: MethodSpec,
    model: ModelSpec,
    env: EnvironmentSpec,
    modality: Modality,
    signal: Signal,
) -> dict:
    entry: dict = {
        "name": naming.eval_method_name(method.base, signal),
        "type": method.type,
        "signal_type": signal.config_signal_type,
    }
    if method.prompt_preset is not None:
        entry["prompt_preset"] = method.prompt_preset
    entry["policy_assumption"] = "optimal"
    entry["backend_name"] = resolve_backend(method, model, modality)
    if method.num_samples is not None:
        entry["num_samples"] = method.num_samples
    # method-level fields first, then environment-specific overrides.
    for key, value in (*method.extra_fields, *env.params_for(method.base)):
        entry[key] = _yamlable(value)
    return entry


def _context_name(env: EnvironmentSpec, modality: Modality) -> str | None:
    if modality is Modality.VISION and env.vision_context_name is not None:
        return env.vision_context_name
    return env.context_name


def _eval_config(
    env: EnvironmentSpec,
    model: ModelSpec,
    modality: Modality,
    *,
    include_ablations: bool,
    registry: Registry,
) -> GeneratedConfig | None:
    points = env.points_for(modality, non_llm=model.is_non_llm)
    entries: list[dict] = []
    # QV block then SV block, methods in catalog order within each.
    for signal in (Signal.QV, Signal.SV):
        for method in registry.methods:
            if method.is_ablation and not include_ablations:
                continue
            if not is_applicable(method, model, env, modality):
                continue
            if signal not in signals_for(method, env, modality):
                continue
            entries.append(_method_entry(method, model, env, modality, signal))
    if not entries:
        return None

    dir_name = naming.eval_dir_name(
        num_points=points, dataset_id=env.dataset_id, actor=model.actor, modality=modality
    )
    body = {
        "backends_config_path": _BACKENDS_CONFIG,
        "dataset_path": env.dataset_path,
        "predictions_dir": f"data/predictions/{env.env}/{dir_name}",
        "batch_size": env.batch_size,
        "discount_factor": env.discount_factor,
        "max_eval_points": points,
        "max_aborted_points": env.max_aborted_points,
        "prediction": {
            "max_history_turns": env.max_history_turns,
            "context_name": _context_name(env, modality),
            "contexts_dir": env.contexts_dir,
        },
        "eval_methods": entries,
    }
    filename = f"{naming.points_token(points)}_{env.dataset_id}_{model.actor}_{modality.value}.yaml"
    return GeneratedConfig(
        path=f"configs/prediction/{env.env}/{filename}",
        text=_render(body),
        kind="eval",
        env=env.env,
    )


def _gt_config(
    env: EnvironmentSpec, gt_actor: str, *, registry: Registry
) -> GeneratedConfig:
    signals = [Signal.QV] + ([Signal.SV] if env.supports_sv else [])
    gt_model = registry.model_by_actor(gt_actor)
    estimations: list[dict] = []
    for signal in signals:
        for agg in env.gt_aggregations:
            est: dict = {
                "name": f"{signal.value}_mc_{agg}",
                "assumption": signal.config_signal_type,
                "method": "mc",
                "aggregation": agg,
                "num_rollouts": env.gt_num_rollouts,
            }
            # Rollout source — fill-in slots (see EnvironmentSpec). The scripted
            # actor uses a scripted policy; an LLM ground-truth actor rolls out
            # with its own backend. Emitted only when known.
            if gt_actor == "scripted":
                if env.gt_policy_name is not None:
                    est["policy_name"] = env.gt_policy_name
            elif gt_model is not None and gt_model.backend_base is not None:
                est["backend_name"] = gt_model.backend_base
            estimations.append(est)

    dir_name = naming.gt_dir_name(
        num_points=env.gt_points, dataset_id=env.dataset_id, gt_actor=gt_actor
    )
    body = {
        "backends_config_path": _BACKENDS_CONFIG,
        "dataset_path": env.dataset_path,
        "predictions_dir": f"data/predictions/{env.env}/{dir_name}",
        "batch_size": env.batch_size,
        "discount_factor": env.discount_factor,
        "max_eval_points": env.gt_points,
        "prediction": {
            "context_name": env.context_name,
            "contexts_dir": env.contexts_dir,
        },
        "estimations": estimations,
        "eval_methods": [],
    }
    filename = f"{naming.points_token(env.gt_points)}_{env.dataset_id}_{gt_actor}_gt.yaml"
    return GeneratedConfig(
        path=f"configs/prediction/{env.env}/{filename}",
        text=_render(body),
        kind="gt",
        env=env.env,
    )


# --- public API ------------------------------------------------------------
def iter_generated_configs(
    *, include_ablations: bool = False, registry: Registry | None = None
) -> list[GeneratedConfig]:
    """All generated configs, in deterministic order (catalog order of envs,
    then modality text→vision, then env actor order; GT configs last per env)."""
    registry = registry or active_registry()
    out: list[GeneratedConfig] = []
    for env in registry.environments:
        modalities = [Modality.TEXT]
        if env.supports_vision:
            modalities.append(Modality.VISION)
        for modality in modalities:
            for actor in env.actors_for(modality):
                model = registry.model_by_actor(actor)
                if model is None:
                    continue
                cfg = _eval_config(
                    env, model, modality,
                    include_ablations=include_ablations, registry=registry,
                )
                if cfg is not None:
                    out.append(cfg)
        for gt_actor in env.gt_actors:
            out.append(_gt_config(env, gt_actor, registry=registry))
    return out


def write_all(
    root: str | Path, *, include_ablations: bool = False, registry: Registry | None = None
) -> list[str]:
    """Write every generated config under ``root``. Returns the paths written."""
    registry = registry or active_registry()
    root = Path(root)
    written: list[str] = []
    for cfg in iter_generated_configs(include_ablations=include_ablations, registry=registry):
        dest = root / cfg.path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(cfg.text)
        written.append(cfg.path)
    return written


def check_drift(
    root: str | Path, *, include_ablations: bool = False, registry: Registry | None = None
) -> list[str]:
    """Report generator-owned files under ``root`` that are missing or stale.

    Only files the generator owns are checked — leftover hand-written configs
    are ignored. Returns a list of human-readable drift descriptions (empty
    when in sync).
    """
    registry = registry or active_registry()
    root = Path(root)
    drift: list[str] = []
    for cfg in iter_generated_configs(include_ablations=include_ablations, registry=registry):
        dest = root / cfg.path
        if not dest.is_file():
            drift.append(f"missing: {cfg.path}")
        elif dest.read_text() != cfg.text:
            drift.append(f"stale: {cfg.path}")
    return drift
