dataset_path: shared/data/datasets/alfworld/200pt_all-types_40ms_ds32_20260414_035138.pkl
output_dir: data/evaluations/alfworld/all-types-40ms_g4-26-or_text

prediction_sources:
  - path: data/predictions/alfworld/GT_200pt_all-types-40ms_scripted/gt
    type: gt
  - path: data/predictions/alfworld/EVAL_100pt_all-types-40ms_g4-26-or_text/eval
    type: eval

comparisons:
  - gt: qv_mc_max
    eval:
      - codegen-mean_qv
      - codegen-s0_qv
      - codegen-s10_qv
      - codegen-s11_qv
      - codegen-s12_qv
      - codegen-s13_qv
      - codegen-s14_qv
      - codegen-s15_qv
      - codegen-s1_qv
      - codegen-s2_qv
      - codegen-s3_qv
      - codegen-s4_qv
      - codegen-s5_qv
      - codegen-s6_qv
      - codegen-s7_qv
      - codegen-s8_qv
      - codegen-s9_qv
      - direct-batch4-packed_qv
      - direct-batch8-seq_qv
      - direct-verif16_qv
      - direct_qv
      - eureka_qv
      - gvl_qv
      - verifier_qv
  - gt: sv_mc_max
    eval:
      - codegen-mean_sv
      - codegen-s0_sv
      - codegen-s10_sv
      - codegen-s11_sv
      - codegen-s12_sv
      - codegen-s13_sv
      - codegen-s14_sv
      - codegen-s15_sv
      - codegen-s1_sv
      - codegen-s2_sv
      - codegen-s3_sv
      - codegen-s4_sv
      - codegen-s5_sv
      - codegen-s6_sv
      - codegen-s7_sv
      - codegen-s8_sv
      - codegen-s9_sv
      - direct-batch4-packed_sv
      - direct-batch8-seq_sv
      - direct-verif16_sv
      - direct_sv
      - eureka_sv
      - gvl_sv
