"""qval: Benchmark for evaluating dense signal functions in RL environments."""

from qval.benchmark import (
    collect_trajectories,
    prepare_display_points,
    resolve_backend,
)
from qval.config import (
    BackendsRegistryConfig,
    BackendConfig,
    BackendSamplingConfig,
    BenchmarkConfig,
    ComparisonConfig,
    CollectionConfig,
    EstimationConfig,
    EvalMethodConfig,
    EvaluationPointsConfig,
    MCRolloutPersistenceConfig,
    OpenRouterProviderPreferences,
    PipelineCollectionConfig,
    PipelineEvaluationConfig,
    PipelinePassAtKConfig,
    PipelinePredictionConfig,
    PipelineTestTimeScalingConfig,
    PredictionConfig,
    PredictionSourceConfig,
    ResumeRankingSubsetConfig,
    TestTimeScalingActorConfig,
    TestTimeScalingSelfConsistencyConfig,
)
from qval.contexts import load_context, load_environment_context
from qval.correlation import compute_correlation, compute_ranking_correlation
from qval.data_cache import Dataset, load_dataset, save_dataset
from qval.dense_signal import (
    BatchDenseSignalFunction,
    DenseSignalFunction,
    DenseSignalMethod,
)
from qval.estimator import (
    aggregate_returns,
    collect_grouped_gt,
    create_gt_method,
)
from qval.evaluation_points import collect_evaluation_points
from qval.experiment_logging import ExperimentLogger, LoggingBackend
from qval.mc_method import MCMethod
from qval.mcts_method import MCTSMethod, MCTSNode
from qval.methods import (
    DeltaBeliefRankingMethod,
    LLMCodeGenMethod,
    LLMDirectMethod,
    LLMEurekaMethod,
    LLMGVLMethod,
    LLMRankingMethod,
    LLMVerifierMethod,
    SDPOShortExpertContinuationRankingMethod,
    SDPORankingMethod,
    RandomBaselineMethod,
)
from qval.optimal_policies import (
    ScriptedBackend,
    ScriptedPolicyConfig,
    get_policy,
    list_policies,
    register_policy,
)
from qval.resource_monitor import ResourceMonitor
from qval.prediction_store import (
    Prediction,
    load_prediction,
    load_predictions_dir,
    load_predictions_from_path,
    load_predictions_from_sources,
    load_predictions_paths,
    save_prediction,
)
from qval.script_utils import (
    annotate_codegen_records,
    create_adapter_env,
    create_backend_from_config,
    chat_template_kwargs_from_config,
    resolve_backend_name,
    sampling_params_from_config,
)
from qval.system_prompts import (
    ENV_PROMPTS,
    SCHEME_EXAMPLES,
    SCHEME_INSTRUCTIONS,
    build_actor_system_prompt,
    build_ranking_sampling_system_prompt,
)
from qval.rollout import trajectory_return
from qval.test_time_scaling import (
    CandidateSelection,
    ConstantCandidateScorer,
    DenseSignalCandidateScorer,
    GuidedActor,
    default_score_candidate_groups,
    run_guided_actor,
    run_guided_actors_batch,
)
from qval.trajectory_store import (
    ObservableTrajectory,
    ObservableTransition,
    from_trajectory_result,
    load_trajectories,
    save_trajectories,
)
from qval.transforms import (
    extract_potential_values,
    sum_per_trajectory,
    transform_predictions,
)
from qval.types import (
    ActionCandidate,
    AggregationMethod,
    CorrelationMethod,
    CorrelationResult,
    EnvironmentContext,
    EvaluationPoint,
    HistoryTurn,
    MethodContext,
    Policy,
    PolicyAssumption,
    RankingCandidateSource,
    RankingPoint,
    RawPointReturns,
    SignalEstimate,
    SignalType,
)

__all__ = [
    "ActionCandidate",
    "AggregationMethod",
    "BackendsRegistryConfig",
    "BatchDenseSignalFunction",
    "BackendConfig",
    "BackendSamplingConfig",
    "BenchmarkConfig",
    "ComparisonConfig",
    "CollectionConfig",
    "CorrelationMethod",
    "CorrelationResult",
    "Dataset",
    "DeltaBeliefRankingMethod",
    "EnvironmentContext",
    "HistoryTurn",
    "DenseSignalFunction",
    "DenseSignalMethod",
    "EstimationConfig",
    "EvalMethodConfig",
    "EvaluationPoint",
    "EvaluationPointsConfig",
    "ExperimentLogger",
    "LLMCodeGenMethod",
    "LLMDirectMethod",
    "LLMEurekaMethod",
    "LLMGVLMethod",
    "LLMRankingMethod",
    "LLMVerifierMethod",
    "LoggingBackend",
    "MCRolloutPersistenceConfig",
    "MCMethod",
    "MCTSMethod",
    "MCTSNode",
    "MethodContext",
    "ObservableTrajectory",
    "ObservableTransition",
    "OpenRouterProviderPreferences",
    "Policy",
    "PolicyAssumption",
    "PipelineCollectionConfig",
    "PipelineEvaluationConfig",
    "PipelinePassAtKConfig",
    "PipelinePredictionConfig",
    "PipelineTestTimeScalingConfig",
    "PredictionConfig",
    "PredictionSourceConfig",
    "Prediction",
    "ENV_PROMPTS",
    "SCHEME_INSTRUCTIONS",
    "SCHEME_EXAMPLES",
    "build_actor_system_prompt",
    "build_ranking_sampling_system_prompt",
    "RandomBaselineMethod",
    "RankingCandidateSource",
    "RankingPoint",
    "RawPointReturns",
    "ResourceMonitor",
    "ResumeRankingSubsetConfig",
    "TestTimeScalingActorConfig",
    "TestTimeScalingSelfConsistencyConfig",
    "SDPOShortExpertContinuationRankingMethod",
    "SDPORankingMethod",
    "SignalEstimate",
    "SignalType",
    "aggregate_returns",
    "annotate_codegen_records",
    "collect_evaluation_points",
    "collect_grouped_gt",
    "collect_trajectories",
    "compute_correlation",
    "compute_ranking_correlation",
    "create_adapter_env",
    "create_backend_from_config",
    "chat_template_kwargs_from_config",
    "resolve_backend_name",
    "sampling_params_from_config",
    "create_gt_method",
    "extract_potential_values",
    "from_trajectory_result",
    "load_dataset",
    "load_context",
    "load_environment_context",
    "load_prediction",
    "load_predictions_dir",
    "load_predictions_from_path",
    "load_predictions_from_sources",
    "load_predictions_paths",
    "load_trajectories",
    "prepare_display_points",
    "resolve_backend",
    "save_dataset",
    "save_prediction",
    "save_trajectories",
    "ScriptedBackend",
    "ScriptedPolicyConfig",
    "register_policy",
    "get_policy",
    "list_policies",
    "sum_per_trajectory",
    "trajectory_return",
    "CandidateSelection",
    "ConstantCandidateScorer",
    "DenseSignalCandidateScorer",
    "GuidedActor",
    "default_score_candidate_groups",
    "run_guided_actor",
    "run_guided_actors_batch",
    "transform_predictions",
]
